# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f9f886445ade581755abc81c59adab4c945e694e9f3f55e77d721c6f4d56eabe8076dc96fe48cb51f5c9dc44cbbe2299c1c12e3e93b4a1bf9f656f664acdf73

test:
  secret_key_base: 37b5666ee934d05277b7a0ce77d3f23e4b0d8a5cd53e6f59699527a6da05ef408b522506d79c79a99798083eb6ed846ed3ce6fbc8a125bed5694e42caac30137

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
