source 'https://rubygems.org'

gem 'pg'
gem 'bcrypt'
gem 'unicorn'
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'jquery-rails'
gem 'rails', '4.2.1'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'jbuilder', '~> 2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'responders'
gem 'rails_12factor'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'webmock', group: :test

group :development, :test do
  gem 'pry'
  gem 'launchy'
  gem 'vcr'
  gem 'capybara'
  gem 'rspec-rails'
  gem 'better_errors'
  gem 'emoji-rspec', git: "git@github.com:carhartl/emoji-rspec.git", branch: "rspec-3" 
  gem 'guard-rspec'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

